T = [0 0 0 1];
P = [0 0 1 1; 0 1 0 1];
net = perceptron;
net.adaptParam.passes = 20;

net = configure(net,P,T);
plotpv(P, T);
linehandle = plotpc(net.IW{1}, net.b{1});
E = 1;
net = init(net);
linehandle = plotpc(net.IW{1}, net.b{1});
while(mse (E));
[net, Y, E] = adapt(net,P,T);
linehandle = plotpc(net.IW{1}, net.b{1}, linehandle);
drawnow;
end;

T = [1 1 1 0];
net = configure(net,P,T);
plotpv(P, T);
linehandle = plotpc(net.IW{1}, net.b{1});
E = 1;
net = init(net);
linehandle = plotpc(net.IW{1}, net.b{1});
while(mse (E));
[net, Y, E] = adapt(net,P,T);
linehandle = plotpc(net.IW{1}, net.b{1}, linehandle);
drawnow;
end;

T = [0 1 1 1];
net = configure(net,P,T);
plotpv(P, T);
linehandle = plotpc(net.IW{1}, net.b{1});
E = 1;
net = init(net);
linehandle = plotpc(net.IW{1}, net.b{1});
while(mse (E));
[net, Y, E] = adapt(net,P,T);
linehandle = plotpc(net.IW{1}, net.b{1}, linehandle);
drawnow;
end;

T = [1 0 0 0];
net = configure(net,P,T);
plotpv(P, T);
linehandle = plotpc(net.IW{1}, net.b{1});
E = 1;
net = init(net);
linehandle = plotpc(net.IW{1}, net.b{1});
while(mse (E));
[net, Y, E] = adapt(net,P,T);
linehandle = plotpc(net.IW{1}, net.b{1}, linehandle);
drawnow;
end;

T = [0 1 1 0];
net = configure(net,P,T);
plotpv(P, T);
linehandle = plotpc(net.IW{1}, net.b{1});
E = 1;
net = init(net);
linehandle = plotpc(net.IW{1}, net.b{1});
while(mse (E));
[net, Y, E] = adapt(net,P,T);
linehandle = plotpc(net.IW{1}, net.b{1}, linehandle);
drawnow;
end;

T = [1 0 0 1];
net = configure(net,P,T);
plotpv(P, T);
linehandle = plotpc(net.IW{1}, net.b{1});
E = 1;
net = init(net);
linehandle = plotpc(net.IW{1}, net.b{1});
while(mse (E));
[net, Y, E] = adapt(net,P,T);
linehandle = plotpc(net.IW{1}, net.b{1}, linehandle);
drawnow;
end;
